openapi: 3.0.0
info:
  title: Progress API
  version: '1.0'
  description: |-
    This API defines progress about the specific activities (assignable Units) is the course to report to the LMS. Main goal is to inform teachers on progress (which activities are completed) and possible indication that the activity was completed, but needs attention of the teacher. 

    Progress is reported on the actities of the LA (based on the UA (assignable units) in the course description.
    Progress is reported when an activity is started or completed, not while the activity is in progress. If the activity is adaptive and will take more time for one student due to addaptive levels, that is not reported.

    Activities have a life cylcle of not-started, started, completed. The not started is the deafult and will not be reported, unless (for some reason) the status goes back to not-started. The abandoned state is to indicate that the activity was started,but will never be completed (optional)

    The API does not force the LA to use a standard for the indication about the quality of the progress. That is optional and is intended to give the LA a way to tell the teacher that the progress was not standard and the teacher is advised to have a look at the LA's dashboard (with a direct url). An LA can provide any scale (1-10, avarage, good, bad) by adding this as text. The LMS should not try to combine these indications for a complete chapter or paragraph.

    Normally this progress is send as events. When the consent flow is completed and both LA and LMS have consent the events are send. 

    At this moment there is no catchup mechanism defined. (we still have discussion if there should be an API to retrieve the progress. we tend to say no..)

    In the progress statement the LA can add the entitlement and course information so the LMS can use that information to efficiently process the events.

    ## Events
    Events generated by the Progress API are :
     - `la.simpleprogress` - send from the LA to the LMS prefereably near realtime so the LMS can show progress for teachers.  


    ## Scopes and Data

    - la.progress - scope needed to send progress events from la to lms
  contact:
    name: Stichting SEM
    url: 'https://stichtingsem.org/'
    email: mcginkel@gmail.com
servers:
  - url: 'https://example.stichtingsem.org/api'
    description: course
paths: {}
components:
  schemas:
    SimpleProgress:
      title: SimpleProgress
      type: object
      x-examples:
        example-1:
          id: 123-bigstring-or-guid-does-not-matter-but-uniquu-for-this-progres-statement
          schemaVersion: 0
          studentEckId: eck1
          studentId: '12345'
          assignableUnitId: '1234566'
          courseId: english-22-high
          status: completed
          timestamp: '20220112T02:55:12'
          additionalInfo: ':)'
          detailsUrl: 'https://course.publisher.com/analisys/1234566/eck1'
      description: ''
      properties:
        id:
          type: string
          description: Unique id
        schemaVersion:
          type: integer
          description: 'schema version of this event/object. Start with 0, inclement when we have changes, so we know how to deserialise.'
        eckId:
          type: string
          description: |-
            The eckid of the student for which the progress is reported.
            one of userid or eckId is required.
        userId:
          type: string
          description: |-
            The id of the student for which the progress is reported. userid. (nledupersonrealId or nledupersonprofileId)
            one of userid or eckId is required.
        assignableUnitId:
          type: string
          description: unit for which progress is reported. This is strongly linked to the id's in the course API (CMI5e)
        courseId:
          type: string
          description: Optional id of the course.
        status:
          type: string
          description: 'New status of the activity. '
          enum:
            - not-started
            - started
            - completed
            - abandoned
        timestamp:
          type: string
          format: date-time
        additionalInfo:
          type: string
          description: |-
            Additional signal to show to teachers about this progress. This could be a signal that all is fine, or that the activity was finished, but not successfull or with so much efford that the teacher is advised that to look at the LA systems dashboards. 
            field is free format, bust should be very short. eg "good","avarage", single digit, smileys, "!" (also see detailsUrl)
          maxLength: 15
          example: ':)'
        detailsUrl:
          type: string
          description: Deeplink to the page of the LA where a teacher can get details on this progress/result.
        pleaseFollowup:
          type: boolean
          description: |-
            Boolean to indicate that the additional info and detailsUrl are provided as an invite to have a closer look at this progress. (follow url for more details)
            This can be used to show a list of signals that the teacher should followup
      required:
        - id
        - assignableUnitId
        - courseId
        - status
        - timestamp
  securitySchemes:
    APIKey:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes:
            la.progress: scope to send progress events to an LMS
